name: Publish

on:
  workflow_call:
    inputs:
      git-tag-prefix:
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joinself/tools
    permissions:
      contents: write
    steps:
      - uses: joinself/actions-public/setup-job@main
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Publish
        env:
          GIT_TAG_PREFIX: ${{ inputs.git-tag-prefix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(${SCRIPTS}/get-new-version)

          git tag -a ${GIT_TAG_PREFIX}${version} -m "${GIT_TAG_PREFIX}${version}"
          git push origin ${GIT_TAG_PREFIX}${version}

          release_notes=$(${SCRIPTS}/git-get-release-notes)
          gh release create "${GIT_TAG_PREFIX}${version}" --prerelease --notes "${release_notes}"
