name: Publish rubygems

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.3-buster
    steps:
      - name: Setup environment
        shell: bash
        run: |
          curl -Lo /tmp/gh.deb https://github.com/cli/cli/releases/download/v2.23.0/gh_2.23.0_linux_amd64.deb
          apt-get install -y /tmp/gh.deb
          curl -Lo /usr/local/bin/slack-release-notification https://static.joinself.com/scripts/slack-release-notification
          chmod +x /usr/local/bin/slack-release-notification
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          SLACK_WEBHOOK_CI_CI: ${{ secrets.SLACK_WEBHOOK_CI_CI }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          chown root:root .
          git config --global user.name ci
          git config --global user.email ops@joinself.com

          version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')
          current_git_tag=$(git tag --merged ${CI_REF_NAME} | sort -V | tail -n 1)
          if [[ "${version}" != "${current_git_tag}" ]]; then
            git tag -a ${version} -m "${version}"
            git push origin ${version}
            subject=$(git log -n 1 --format=%s)
            body=$(git log -n 1 --format=%b | grep -E '^\*|^-' | sed 's/^*/-/g') || true
            if [[ -z ${body} ]]; then
              release_notes="- ${subject}"
            else
              release_notes="${body}"
            fi
            gh release create "${version}" --notes "${release_notes}"

            gem push selfsdk-${version}.gem
            slack-release-notification -v ${version}
          else
            echo "Version hasn't changed. Nothing to do here."
          fi
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
