name: Secret scan

on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:v8.16.2
      options: "--user root"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Secret scan
        shell: bash
        run: |
          chown root:root .
          wget -O /tmp/gitleaks.toml https://static.joinself.com/gitleaks/gitleaks.toml
          gitleaks -c /tmp/gitleaks.toml detect
        continue-on-error: ${{ inputs.continue-on-error }}
