name: Secret scan

on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:v8.16.2
      options: "--user root"
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Secret scan
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          chown root:root .
          wget -O /tmp/gitleaks.toml https://static.joinself.com/gitleaks/gitleaks.toml
          gitleaks -c /tmp/gitleaks.toml detect
        continue-on-error: ${{ inputs.continue-on-error }}
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
